In [1]:
from mlp import mlp

import numpy as np

import matplotlib.pyplot as plt

In [21]:
gold = mlp()

d_bits = 32
q_bits = 0

gold.set_quant(quant = False)

gold.net_shape([3,5])

gold.init_params(mode="uniform")

0

In [22]:
gold._weight = np.round(np.multiply(gold._weight, 32))

gold._bias = np.round(np.multiply(gold._bias, 32))

x_in = np.array([[1],[2],[3]])

y_truth = np.array([[7],[7],[7],[7],[7]])

In [24]:
print(gold._weight)

print(gold._bias)

[[[15.  8. 27.]
  [32.  0. 29.]
  [32. 22. 29.]
  [28. 11. 17.]
  [ 5.  6. 24.]]]
[[[29.]
  [31.]
  [13.]
  [ 7.]
  [16.]]]


In [25]:
gold.infer(x_in)

gold.grad(y_truth)

gold.print_grad()

Weight Gradient Layer 0:
[[ 268.  536.  804.]
 [ 286.  572.  858.]
 [ 338.  676. 1014.]
 [ 202.  404.  606.]
 [ 196.  392.  588.]]


Bias Gradient Layer 0:
[[268.]
 [286.]
 [338.]
 [202.]
 [196.]]


Activation Gradient Layer 0:
[[30624.]
 [12978.]
 [33470.]]


Activation Gradient Layer 1:
[[268.]
 [286.]
 [338.]
 [202.]
 [196.]]


