In [9]:
import autograd.numpy as np

from autograd import grad

# import numpy as np

from mlp4autograd import mlp4autograd


In [10]:
ref = mlp4autograd()

ref.set_quant(quant = False)

ref.net_shape([3,5])

ref.init_params(mode="uniform")

scale = 8

for i in range(len(ref._weight)):

    ref._weight[i] = np.round(np.multiply(ref._weight[i], scale))
    ref._bias[i] = np.round(np.multiply(ref._bias[i], scale))

params = [ref._weight, ref._bias]

x_in = np.array([[1.0],[2.0],[3.0]])

In [11]:
y_truth = np.array([[16.],
                    [26.],
                    [36.],
                    [36.],
                    [36.]])

def error(params):

    ref.infer(x_in, params)

    return ref.error(y_truth)

In [6]:
for p in params:

    for i in p:

        print(i)

[[0. 6. 7.]
 [5. 3. 6.]
 [4. 3. 0.]
 [3. 3. 4.]
 [8. 1. 1.]]
[[5.]
 [4.]
 [7.]
 [2.]
 [6.]]


In [7]:
ref.infer(x_in, params)
ref.grad(y_truth, False)

# print(ref._activation[-1])

# ref.print_grad()

([array([[  44.,   88.,  132.],
         [  14.,   28.,   42.],
         [ -38.,  -76., -114.],
         [ -26.,  -52.,  -78.],
         [ -34.,  -68., -102.]])],
 [array([[ 44.],
         [ 14.],
         [-38.],
         [-26.],
         [-34.]])])

In [8]:
gradient = grad(error)

grad_eval = gradient(params)

print(grad_eval)

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('O') to dtype('float64') with casting rule 'same_kind'